// <auto-generated />
using System;
using Armament.Persistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Armament.Persistence.Migrations
{
    [DbContext(typeof(ArmamentDbContext))]
    partial class ArmamentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Armament.Persistence.Data.AccountCharacterEntity", b =>
                {
                    b.Property<long>("AccountCharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AccountCharacterId"));

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("integer");

                    b.HasKey("AccountCharacterId");

                    b.HasIndex("CharacterId");

                    b.HasIndex("AccountId", "CharacterId")
                        .IsUnique()
                        .HasDatabaseName("ux_account_character_mapping");

                    b.HasIndex("AccountId", "SlotIndex")
                        .IsUnique()
                        .HasDatabaseName("ux_account_character_slot");

                    b.ToTable("account_characters", (string)null);
                });

            modelBuilder.Entity("Armament.Persistence.Data.AccountEntity", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ExternalSubject")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AccountId");

                    b.HasIndex("ExternalSubject")
                        .IsUnique()
                        .HasDatabaseName("ux_accounts_external_subject");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("Armament.Persistence.Data.CharacterEntity", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<int>("Alacrity")
                        .HasColumnType("integer");

                    b.Property<string>("BaseClassId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Constitution")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Currency")
                        .HasColumnType("integer");

                    b.Property<long>("Experience")
                        .HasColumnType("bigint");

                    b.Property<string>("GearJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("InventoryJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("LearnedRecipesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("MaxBuilderResource")
                        .HasColumnType("integer");

                    b.Property<int>("MaxHealth")
                        .HasColumnType("integer");

                    b.Property<int>("MaxSpenderResource")
                        .HasColumnType("integer");

                    b.Property<int>("Might")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("QuestProgressJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("SpecId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Will")
                        .HasColumnType("integer");

                    b.HasKey("CharacterId");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_characters_name");

                    b.ToTable("characters", (string)null);
                });

            modelBuilder.Entity("Armament.Persistence.Data.InventoryItemEntity", b =>
                {
                    b.Property<long>("InventoryItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("InventoryItemId"));

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("InventoryItemId");

                    b.HasIndex("CharacterId", "ItemCode")
                        .IsUnique()
                        .HasDatabaseName("ux_inventory_character_item");

                    b.ToTable("inventory_items", (string)null);
                });

            modelBuilder.Entity("Armament.Persistence.Data.LearnedRecipeEntity", b =>
                {
                    b.Property<long>("LearnedRecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("LearnedRecipeId"));

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<string>("RecipeCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("LearnedRecipeId");

                    b.HasIndex("CharacterId", "RecipeCode")
                        .IsUnique()
                        .HasDatabaseName("ux_recipe_character_code");

                    b.ToTable("learned_recipes", (string)null);
                });

            modelBuilder.Entity("Armament.Persistence.Data.LootClaimEntity", b =>
                {
                    b.Property<long>("LootClaimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("LootClaimId"));

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ClaimedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PickupToken")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("LootClaimId");

                    b.HasIndex("CharacterId");

                    b.HasIndex("PickupToken")
                        .IsUnique()
                        .HasDatabaseName("ux_loot_claims_pickup_token");

                    b.ToTable("loot_claims", (string)null);
                });

            modelBuilder.Entity("Armament.Persistence.Data.QuestProgressEntity", b =>
                {
                    b.Property<long>("QuestProgressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("QuestProgressId"));

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<int>("ProgressValue")
                        .HasColumnType("integer");

                    b.Property<string>("QuestCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("QuestProgressId");

                    b.HasIndex("CharacterId", "QuestCode")
                        .IsUnique()
                        .HasDatabaseName("ux_quest_character_code");

                    b.ToTable("quest_progress", (string)null);
                });

            modelBuilder.Entity("Armament.Persistence.Data.AccountCharacterEntity", b =>
                {
                    b.HasOne("Armament.Persistence.Data.AccountEntity", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Armament.Persistence.Data.CharacterEntity", "Character")
                        .WithMany("AccountCharacters")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Armament.Persistence.Data.InventoryItemEntity", b =>
                {
                    b.HasOne("Armament.Persistence.Data.CharacterEntity", "Character")
                        .WithMany("InventoryItems")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Armament.Persistence.Data.LearnedRecipeEntity", b =>
                {
                    b.HasOne("Armament.Persistence.Data.CharacterEntity", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Armament.Persistence.Data.LootClaimEntity", b =>
                {
                    b.HasOne("Armament.Persistence.Data.CharacterEntity", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Armament.Persistence.Data.QuestProgressEntity", b =>
                {
                    b.HasOne("Armament.Persistence.Data.CharacterEntity", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Armament.Persistence.Data.CharacterEntity", b =>
                {
                    b.Navigation("AccountCharacters");

                    b.Navigation("InventoryItems");
                });
#pragma warning restore 612, 618
        }
    }
}
